package com.example.userservice.exception;

public class AppMessages {
    public static final String USER_NOT_FOUND_BY_ID = "User with ID '%s' not found";

    public static final String USER_NOT_FOUND = "User not found";
    public static final String ACCESS_DENIED = "Access Denied";
    public static final String VALIDATION_ERROR_TITLE = "Validation Error";
    public static final String ACCESS_DENIED_TITLE = "You do not have permission to perform this action";
    public static final String CUSTOM_ERROR_TITLE = "Custom Error";
    public static final String UNEXPECTED_ERROR_TITLE = "Unexpected Error";
    public static final String DUPLICATE_KEY_TITLE = "Duplicate Key";
    public static final String RESOURCE_ALREADY_EXISTS = "Resource already exists";


}
